---
- name: Setup config files and personal scripts
  hosts: all
  vars: 
    ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Clone dotfiles
      ansible.builtin.git:
        repo: git@github.com:ametis70/dotfiles.git
        dest: ~/.local/share/dotmix        
        accept_newhostkey: true
    
    - name: Clone personal scripts
      ansible.builtin.git:
        repo: git@github.com:ametis70/bin.git
        dest: ~/.bin        
        accept_newhostkey: true
