---
- name: Setup local email
  hosts: archlinux

  tasks:
    - name: Install official repository packages
      community.general.pacman:
        name:
          - isync
          - goimapnotify
        state: present
      become: yes

    - name: Install AUR packages
      community.general.pacman:
        name: mu
        state: present
        executable: yay

    - name: Start imapnotify service
      ansible.builtin.systemd:
        name: goimapnotify@ianmancini.service
        scope: user
        state: started
        enabled: yes
