---
- name: Setup secrets related packages and settings
  hosts: all
  vars: 
    ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Install secrets packages
      community.general.pacman:
        name:
          - libsecret
          - gnome-keyring
          - seahorse
          - gnupg
          - pass
        state: latest
        update_cache: true
      become: yes

    - name: Set Gnome Keyring auth PAM rule
      community.general.pamd:
        name: login
        type: auth
        control: include
        module_path: system-local-login
        new_type: auth
        new_control: optional 
        new_module_path: pam_gnome_keyring.so
        state: after
      become: yes

    - name: Set Gnome Keyring session PAM rule
      community.general.pamd:
        name: login
        type: session
        control: include
        module_path: system-local-login
        new_type: session
        new_control: optional 
        new_module_path: pam_gnome_keyring.so
        module_arguments: 'auto_start'
        state: after
      become: yes

    - name: Set gnome3-pinentry as GnuPG pinentry dialog 
      ansible.builtin.lineinfile:
        path: ~/.gnupg/gpg-agent.conf
        regexp: '^pinentry-program'
        line: pinentry-program /usr/bin/pinentry-gnome3
        create: true
